version: '3.3'

services:
  mongo:
    image: mongo:${MONGO_IMAGE:-4}
    restart: always
    #    ports: # for local development only
    #      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS:-secret}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE:-cultural}
    volumes:
      - ${MONGO_DATA_PATH:-./mongo-data}:/data/db
    logging:
      driver: none

  cultural:
    depends_on:
      - mongo
    image: docker.pkg.github.com/sausageroll/cultural-footprint/cultural_footprint:${CULTURAL_IMAGE:-latest}
    restart: always
    #    ports:
    #      - "8080:8080"
    environment:
      MONGO_HOST: mongo
      MONGO_USER: ${MONGO_USER:-root}
      MONGO_PASS: ${MONGO_PASS:-secret}

    logging:
      driver: json-file
      options:
        max-size: 10M
        max-file: "3"

  analysis:
    image: docker.pkg.github.com/romangr/culturalfootprintanalysis/culturalfootprintanalysis:${CULTURAL_ANALYSIS_IMAGE:-latest}
    restart: always
    environment:
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      MONGO_USERNAME: ${MONGO_USER:-root}
      MONGO_PASSWORD: ${MONGO_PASS:-secret}
      MONGO_DATABASE: cultural
      N_CLUSTERS: 50
    logging:
      driver: json-file
      options:
        max-size: 10M
        max-file: "3"

  nginx:
    image: nginx:1.18-alpine
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ~/nginx-conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/ssl/cultural.romangr.ru.crt:/etc/ssl/cultural.romangr.ru.crt:ro
      - /etc/ssl/cultural.romangr.ru.key:/etc/ssl/cultural.romangr.ru.key:ro
      - ~/admin-ui:/serve:ro
    logging:
      driver: json-file
      options:
        max-size: 10M
        max-file: "3"
