- name: Deploy Cultural Analysis service
  hosts: all
  gather_facts: yes
  vars:
    timestamp: "{{ ansible_date_time.epoch }}"
  tasks:
    - name: Deployment block
      block:
        - name: Create deployment folder
          file:
            path: ~/deploy-{{ timestamp }}
            state: directory

        - name: Copy compose file
          copy:
            src: ../docker-compose.yml
            dest: ~/deploy-{{ timestamp }}/docker-compose.yml

        - name: Nginx config stat
          stat:
            path: ~/nginx-conf/nginx.conf
            register: nginx_config_stat

        - name: Copy Nginx config
          copy:
            src: ../nginx-conf/nginx.conf
            dest: /etc/nginx/nginx.conf
          when: !nginx_config_stat.exists

        - name: Cert stat
          stat:
            path: ~/ssl/cultural.romangr.ru.crt
            register: cert_stat

        - name: Key stat
          stat:
            path: ~/ssl/cultural.romangr.ru.key
            register: key_stat

        - name: Key and cert exist
          fail:
            msg: "Key and/or cert doesn't exist"
          when: "!cert_stat.stat.exists || !key_stat.stat.exists"

        - name: Start up application
          docker_compose:
            project_src: ~/deploy-{{ timestamp }}
            project_name: cultural_footprint
            services: nginx
            state: present
            restarted: true

      always:
        - name: Remove deployment folder
          file:
            path: ~/deploy-{{ timestamp }}
            state: absent
