- name: Deploy Cultural Analysis service
  hosts: all
  gather_facts: yes
  vars:
    timestamp: "{{ ansible_date_time.epoch }}"
  tasks:
    - name: Deployment block
      block:
        - name: Create deployment folder
          file:
            path: ~/deploy-{{ timestamp }}
            state: directory

        - name: Copy compose file
          copy:
            src: ../docker-compose.yml
            dest: ~/deploy-{{ timestamp }}/docker-compose.yml

        - name: Create config folder
          file:
            path: ~/nginx-conf
            state: directory

        - name: Copy Nginx config
          copy:
            src: ../nginx-conf/nginx.conf
            dest: ~/nginx-conf/nginx.conf

        - name: Start up application
          docker_compose:
            project_src: ~/deploy-{{ timestamp }}
            project_name: cultural_footprint
            services: nginx
            state: present
            restarted: true

      always:
        - name: Remove deployment folder
          file:
            path: ~/deploy-{{ timestamp }}
            state: absent
